### ISSUE TITLE
Javascript errors after recent update

### ISSUE THREAD

**Issue by reallyuniquename** [gurnec/removeddit#11]
Recently Unddit stopped working for me on some legacy browsers with the following error in the console.
```
SyntaxError: bad method definition  @main.js:2:241784
```

Would you mind taking a look?

**Comment by gurnec** [comment]
Below is the current list of supported browsers, more or less. Do you see yours listed? If not, which browser(s) aren't working?

```
android chrome/edge 112
android firefox 110
android qq 13.1
android uc 13.4
android webview 112
chrome 112
chrome 111
chrome 110
chrome 109
edge 112
edge 111
edge 110
firefox 112
firefox 111
firefox 110
firefox 102
ios safari 16.4
ios safari 16.3
ios safari 16.2
ios safari 16.1
ios safari 16.0
ios safari 15.6
kaios 3.0-3.1
kaios 2.5
opera mini all
opera mobile 73
opera 95
opera 94
safari 16.4
safari 16.3
safari 15.6
samsung 20
samsung 19.0
```

**Comment by reallyuniquename** [comment]
It works on latest Chrome and Firefox just fine but it stopped working this week on [Waterfox Classic](https://github.com/WaterfoxCo/Waterfox-Classic/releases) that is based on Firefox 56.

**Comment by gurnec** [comment]
Can you see if this is working for you now? Thanks!

https://staging.unddit.com/about

Please note the different domain name, `staging.unddit.com`, when testing this out with a Reddit post.

**Comment by reallyuniquename** [comment]
Yeah, staging works!
