### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by oifj34f34f** [gurnec/removeddit#14]
Could not connect to Reddit

**Comment by oifj34f34f** [comment]
It worked now (https://undelete.pullpush.io/)

**Comment by MasterInQuestion** [comment]
For reference:
    "Could not get removed comments"
    E.g. https://undelete.pullpush.io/r/ProtonMail/comments/1jn9iuq
    .
    HTTP 502 Bad Gateway:
    https://api.pullpush.io/reddit/comment/search/?fields=author,body,created_utc,id,link_id,parent_id,retrieved_on,retrieved_utc,score,subreddit&metadata=true&size=100&sort=asc&link_id=1jn9iuq
    [ ^ Online again as of 2025-04-02. ]
