### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by ajaxwalk** [gurnec/removeddit#6]
Hi! 

Thanks for this great project, the only thing that I miss is the possibility to have an optional light theme!

Regards!

**Comment by gurnec** [comment]
Blasphemy!! Removeddit/Unddit are ~infamous~ famous for their ~overly~ uniquely saturated dark mode!

Seriously though, I've been working on a *non-default* light mode which should be ready in the near future. Thanks for the suggestion!

**Comment by ajaxwalk** [comment]
![awesome](https://user-images.githubusercontent.com/93199147/162207680-8f4df6d4-55d9-4d70-b05c-91edc6c372b5.gif)


Thank you! It was quick af!
