### ISSUE TITLE
Compatibility with libreddit

### ISSUE THREAD

**Issue by PAI5REECHO** [gurnec/removeddit#8]
It'd be nice to have this working with libredd.it if possible

**Comment by gurnec** [comment]
I'm aware of libredd.it, but I don't understand what you'd like to see... could you be more specific please?

**Comment by PAI5REECHO** [comment]
Sorry I thought the bookmarklet was supposed to add the deleted messages into the DOM, my bad. I see it just does a quick redirect for convenience.

**Comment by PAI5REECHO** [comment]
I'll just make my own userscript since it's out of scope
